import type { LookSettings } from "./looks";

/**
 * Built in looks, shipped alongside the user's own library. Each one pairs a
 * shape with a ripple outline and a reward mode that suit it, colors checked
 * for contrast against the backdrop (button 3:1 or better, ripples 2.5:1 or
 * better), and one of Pulsar's expressive presets as the tap haptic. Half sit
 * on dark grounds and half on light ones.
 */
export interface Preset {
  id: string;
  name: string;
  /** One line on what it feels like. */
  tagline: string;
  look: LookSettings;
}

const preset = (
  id: string,
  name: string,
  tagline: string,
  look: Omit<LookSettings, "randomColors" | "returnToIdle" | "rippleFollowButton"> &
    Partial<Pick<LookSettings, "randomColors" | "returnToIdle" | "rippleFollowButton">>,
): Preset => ({
  id,
  name,
  tagline,
  look: {
    randomColors: false,
    returnToIdle: false,
    rippleFollowButton: false,
    ...look,
  },
});

export const PRESETS: Preset[] = [
  preset("tide-pool", "Tide Pool", "Cascading teal rings and a surge underfoot.", {
    shape: "circle",
    rewardMode: "wave",
    rippleShape: "round",
    rippleLinger: 1500,
    rippleMax: 4,
    rippleWidth: "normal",
    idleColor: "#5EEAD4",
    tapColors: ["#5EEAD4", "#22D3EE", "#A5F3FC"],
    rippleColors: ["#67E8F9", "#99F6E4", "#38BDF8"],
    backdrop: "#04263A",
    hapticStrength: 0.8,
    tapPreset: "tidalSurge",
  }),
  preset("peach-sorbet", "Peach Sorbet", "A slow bloom on a warm, pale ground.", {
    shape: "squircle",
    rewardMode: "soft",
    rippleShape: "match",
    rippleLinger: 1500,
    rippleMax: 2,
    rippleWidth: "thick",
    idleColor: "#EA580C",
    tapColors: ["#EA580C", "#E11D48", "#B45309"],
    rippleColors: ["#E11D48", "#EA580C", "#BE123C"],
    backdrop: "#FFE9D6",
    hapticStrength: 0.45,
    tapPreset: "bloom",
  }),
  preset("ember", "Ember", "Hot orange on near black, with a bass drop.", {
    shape: "hexagon",
    rewardMode: "deep",
    rippleShape: "match",
    rippleLinger: 600,
    rippleMax: 2,
    rippleWidth: "thick",
    idleColor: "#FF6A00",
    tapColors: ["#FF6A00", "#FFB020", "#FF3D00"],
    rippleColors: ["#FF8A3D", "#FFC66B", "#FF5722"],
    backdrop: "#1A0A05",
    hapticStrength: 1.5,
    tapPreset: "bassDrop",
  }),
  preset("moonlit", "Moonlit", "The icon's navy with silver rings and a lighthouse sweep.", {
    shape: "circle",
    rewardMode: "original",
    rippleShape: "wavy",
    rippleLinger: 600,
    rippleMax: 3,
    rippleWidth: "normal",
    idleColor: "#F4F4F5",
    tapColors: ["#F4F4F5", "#C7D2FE", "#E0E7FF"],
    rippleColors: ["#C7D2FE", "#A5B4FC", "#E0E7FF"],
    backdrop: "navy",
    hapticStrength: 0.8,
    tapPreset: "lighthouse",
  }),
  preset("meadow", "Meadow", "Greens on mint, thin ripples that rustle.", {
    shape: "blob",
    rewardMode: "wave",
    rippleShape: "match",
    rippleLinger: 600,
    rippleMax: 5,
    rippleWidth: "thin",
    idleColor: "#15803D",
    tapColors: ["#15803D", "#4D7C0F", "#0F766E"],
    rippleColors: ["#15803D", "#4D7C0F", "#0F766E"],
    backdrop: "#E3FFF3",
    hapticStrength: 0.8,
    tapPreset: "rustle",
  }),
  preset("neon-arcade", "Neon Arcade", "Electric colors at random, a glitchy snap.", {
    shape: "square",
    rewardMode: "spark",
    rippleShape: "round",
    rippleLinger: 0,
    rippleMax: 5,
    rippleWidth: "thin",
    idleColor: "#39FF14",
    tapColors: ["#39FF14", "#FF2D95", "#00E5FF", "#FFE600"],
    randomColors: true,
    rippleColors: ["#FF2D95", "#00E5FF", "#FFE600"],
    backdrop: "#000000",
    hapticStrength: 1,
    tapPreset: "glitch",
  }),
  preset("rose-quartz", "Rose Quartz", "A heart that beats twice on pale pink.", {
    shape: "heart",
    rewardMode: "double",
    rippleShape: "match",
    rippleLinger: 1500,
    rippleMax: 2,
    rippleWidth: "normal",
    idleColor: "#E11D48",
    tapColors: ["#E11D48", "#DB2777", "#BE185D"],
    rippleColors: ["#BE123C", "#9D174D", "#E11D48"],
    backdrop: "#FFE4F1",
    hapticStrength: 0.8,
    tapPreset: "heartbeat",
  }),
  preset("deep-sea", "Deep Sea", "Wavy rings that linger, and a sonar ping.", {
    shape: "ripples",
    rewardMode: "deep",
    rippleShape: "wavy",
    rippleLinger: 3000,
    rippleMax: 3,
    rippleWidth: "thick",
    idleColor: "#0EA5E9",
    tapColors: ["#0EA5E9", "#3B82F6", "#06B6D4"],
    rippleColors: ["#38BDF8", "#818CF8", "#22D3EE"],
    backdrop: "#020B1A",
    hapticStrength: 1,
    tapPreset: "sonar",
  }),
  preset(
    "lavender-haze",
    "Lavender Haze",
    "Soft violet that drifts back to rest, feather light.",
    {
      shape: "squircle",
      rewardMode: "soft",
      rippleShape: "round",
      rippleLinger: 3000,
      rippleMax: 2,
      rippleWidth: "thick",
      idleColor: "#6D28D9",
      tapColors: ["#6D28D9", "#5B21B6", "#7E22CE"],
      returnToIdle: true,
      rippleColors: ["#6D28D9", "#A21CAF", "#7C3AED"],
      backdrop: "#EEE6FF",
      hapticStrength: 0.45,
      tapPreset: "feather",
    },
  ),
  preset("thunderhead", "Thunderhead", "Lightning yellow on slate, a rolling thunder hit.", {
    shape: "hexagon",
    rewardMode: "deep",
    rippleShape: "wavy",
    rippleLinger: 600,
    rippleMax: 3,
    rippleWidth: "thick",
    idleColor: "#FACC15",
    tapColors: ["#FACC15", "#F4F4F5", "#FDE68A"],
    rippleColors: ["#FDE68A", "#E5E7EB", "#FACC15"],
    backdrop: "#1F2933",
    hapticStrength: 2,
    tapPreset: "thunderRoll",
  }),
  preset("citrus", "Citrus", "A star that crackles like a firecracker on pale yellow.", {
    shape: "star",
    rewardMode: "spark",
    rippleShape: "match",
    rippleLinger: 0,
    rippleMax: 4,
    rippleWidth: "thin",
    idleColor: "#EA580C",
    tapColors: ["#EA580C", "#DC2626", "#B45309"],
    rippleColors: ["#DC2626", "#B45309", "#EA580C"],
    backdrop: "#FFF7CC",
    hapticStrength: 1,
    tapPreset: "firecracker",
  }),
  preset("aurora", "Aurora", "Mint, violet, and pink unfurling over the night.", {
    shape: "blob",
    rewardMode: "wave",
    rippleShape: "wavy",
    rippleLinger: 1500,
    rippleMax: 5,
    rippleWidth: "normal",
    idleColor: "#34D399",
    tapColors: ["#34D399", "#A78BFA", "#22D3EE", "#F472B6"],
    randomColors: true,
    rippleColors: ["#A78BFA", "#34D399", "#F472B6"],
    backdrop: "#06121F",
    hapticStrength: 0.8,
    tapPreset: "unfurl",
  }),
  preset("snowfall", "Snowfall", "Ink on white, slow thin circles, a single dewdrop.", {
    shape: "circle",
    rewardMode: "soft",
    rippleShape: "round",
    rippleLinger: 3000,
    rippleMax: 3,
    rippleWidth: "thin",
    idleColor: "#0F172A",
    tapColors: ["#0F172A", "#334155", "#1E3A8A"],
    rippleColors: ["#475569", "#64748B", "#1E293B"],
    backdrop: "#FFFFFF",
    hapticStrength: 0.45,
    tapPreset: "dewdrop",
  }),
  preset("cherry-cola", "Cherry Cola", "Reds on a dark bottle, with a coin drop.", {
    shape: "squircle",
    rewardMode: "pulse",
    rippleShape: "match",
    rippleLinger: 600,
    rippleMax: 3,
    rippleWidth: "normal",
    idleColor: "#FF3B3B",
    tapColors: ["#FF3B3B", "#F43F5E", "#FB7185"],
    rippleColors: ["#FB7185", "#F43F5E", "#FDA4AF"],
    backdrop: "#14060A",
    hapticStrength: 1,
    tapPreset: "coinDrop",
  }),
  preset("honey", "Honey", "Golden heart, two circles, a bright plink.", {
    shape: "heart",
    rewardMode: "double",
    rippleShape: "round",
    rippleLinger: 600,
    rippleMax: 2,
    rippleWidth: "normal",
    idleColor: "#FFD166",
    tapColors: ["#FFD166", "#FFF1C1", "#F4A261"],
    rippleColors: ["#FFE8A3", "#F4A261", "#FFD166"],
    backdrop: "#3B2A08",
    hapticStrength: 0.8,
    tapPreset: "plink",
  }),
  preset("coral-reef", "Coral Reef", "Coral square on pale blue, a firm knock.", {
    shape: "square",
    rewardMode: "pulse",
    rippleShape: "match",
    rippleLinger: 600,
    rippleMax: 3,
    rippleWidth: "normal",
    idleColor: "#E63946",
    tapColors: ["#E63946", "#D62828", "#C2410C"],
    rippleColors: ["#E63946", "#C2410C", "#D62828"],
    backdrop: "#E0F2FF",
    hapticStrength: 1,
    tapPreset: "knock",
  }),
  preset(
    "midnight-garden",
    "Midnight Garden",
    "A pink star over deep green, a cascade of taps.",
    {
      shape: "star",
      rewardMode: "wave",
      rippleShape: "match",
      rippleLinger: 1500,
      rippleMax: 4,
      rippleWidth: "thin",
      idleColor: "#F472B6",
      tapColors: ["#F472B6", "#C084FC", "#FDE68A"],
      rippleColors: ["#86EFAC", "#F9A8D4", "#FDE68A"],
      backdrop: "#0B1F12",
      hapticStrength: 0.8,
      tapPreset: "cascade",
    },
  ),
  preset("obsidian", "Obsidian", "Silver on black, standing rings, an anvil strike.", {
    shape: "hexagon",
    rewardMode: "original",
    rippleShape: "match",
    rippleLinger: 600,
    rippleMax: 3,
    rippleWidth: "thin",
    idleColor: "#D4D4D8",
    tapColors: ["#D4D4D8", "#F4F4F5", "#A1A1AA"],
    rippleColors: ["#A1A1AA", "#71717A", "#D4D4D8"],
    backdrop: "#000000",
    hapticStrength: 1.5,
    tapPreset: "anvil",
  }),
  preset("bubblegum", "Bubblegum", "White on hot pink, thick circles, a balloon pop.", {
    shape: "blob",
    rewardMode: "double",
    rippleShape: "round",
    rippleLinger: 600,
    rippleMax: 3,
    rippleWidth: "thick",
    idleColor: "#FFFFFF",
    tapColors: ["#FFFFFF", "#FFF4B8", "#D6FAFF"],
    rippleColors: ["#FFFFFF", "#FFF4B8", "#D6FAFF"],
    backdrop: "#D1157A",
    hapticStrength: 1,
    tapPreset: "balloonPop",
  }),
  preset("zen", "Zen", "Stone on paper, one slow circle, a breath.", {
    shape: "circle",
    rewardMode: "soft",
    rippleShape: "round",
    rippleLinger: 3000,
    rippleMax: 1,
    rippleWidth: "thin",
    idleColor: "#57534E",
    tapColors: ["#57534E", "#78716C", "#44403C"],
    returnToIdle: true,
    rippleColors: ["#78716C", "#57534E", "#44403C"],
    backdrop: "#F4F1EA",
    hapticStrength: 0.45,
    tapPreset: "breath",
  }),
];
